#!/usr/bin/env bash

# Usage: git-repo-stats
#
# Print stats about every commit in a Git repository.
#
# Dependencies: bash, git, and GNU utils

set -o nounset
set -o errexit

function GitRepoStats {
  paste <(GitCommits "$@") <(GitCommits "$@" | cut -f1 | GitStats)
}

# List core information about all commits
function GitCommits {
  git log --date=short --pretty="tformat:%h	%ad	%an" "$@"
}

# List stats for all supplied commit hashes
function GitStats {
  while read -r sha
  do
    GitCommitStats "$sha"
  done
}

# Print stats for the given commit hash
function GitCommitStats {
  git show --pretty=oneline --numstat "$@" \
    | sed '1d' \
    | grep -v '^$' \
    | sed 's/\-	/0	/g' \
    | awk -v OFS='\t' \
      '
        BEGIN { files=0; added=0; removed=0; }
        { files+=1; added+=$1; removed+=$2; }
        END { print files, added, removed; }
      '
}

GitRepoStats "$@"
